# Generated by Django 3.2.7 on 2021-09-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='Əlaqə Nömrəsi')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Əlaqə məlumatı',
                'verbose_name_plural': 'Əlaqə məlumatları',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='logo/images')),
            ],
            options={
                'verbose_name': 'Loqo',
                'verbose_name_plural': 'Loqo',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders/images/')),
                ('text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Slayderlər',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=50, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Sosial Şəbəkə',
                'verbose_name_plural': 'Sosial Şəbəkələr',
            },
        ),
    ]
