# Generated by Django 3.2.7 on 2021-09-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210922_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
