# Generated by Django 3.2.7 on 2021-09-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_infoblock_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoblock',
            name='image',
        ),
    ]
