# Generated by Django 3.2.7 on 2021-09-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20210921_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antalya',
            name='prise',
            field=models.CharField(max_length=20),
        ),
    ]
