# Generated by Django 3.2.7 on 2021-09-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_antalya_prise'),
    ]

    operations = [
        migrations.AddField(
            model_name='antalyaimages',
            name='antalya',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.antalya'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antalyaimages',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
