# Generated by Django 3.2.7 on 2021-09-21 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20210921_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antalyaimages',
            name='antalya',
        ),
        migrations.AddField(
            model_name='antalya',
            name='antalyaimages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.antalyaimages'),
            preserve_default=False,
        ),
    ]
