# Generated by Django 3.2.7 on 2021-09-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_auto_20210921_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antalya',
            name='antalyaimages',
        ),
        migrations.AddField(
            model_name='antalya',
            name='antalyaimages',
            field=models.ManyToManyField(to='tour.AntalyaImages'),
        ),
    ]
