# Generated by Django 3.2.7 on 2021-09-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_auto_20210921_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antalyaimages',
            old_name='image',
            new_name='picture',
        ),
    ]
