# Generated by Django 3.2.7 on 2021-09-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antalya',
            old_name='show_popular_tur',
            new_name='show_popular',
        ),
    ]
