# Generated by Django 3.2.7 on 2021-09-23 09:52

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_rename_show_popular_tur_antalya_show_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alanya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_popular', models.BooleanField(default=False, verbose_name='Tüm turlarda göstər')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Alanya/images')),
                ('prise', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Alanya Tur',
                'verbose_name_plural': 'Alanya Turları',
            },
        ),
        migrations.CreateModel(
            name='Belek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_popular', models.BooleanField(default=False, verbose_name='Tüm turlarda göstər')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Belek/images')),
                ('prise', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Belek Tur',
                'verbose_name_plural': 'Belek Turları',
            },
        ),
        migrations.CreateModel(
            name='Kemer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_popular', models.BooleanField(default=False, verbose_name='Tüm turlarda göstər')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Kemer/images')),
                ('prise', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Kemer Tur',
                'verbose_name_plural': 'Kemer Turları',
            },
        ),
        migrations.CreateModel(
            name='Kiralama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_popular', models.BooleanField(default=False, verbose_name='Tüm turlarda göstər')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Kiralama/images')),
                ('prise', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Kiralama Tur',
                'verbose_name_plural': 'Kiralama Turları',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_popular', models.BooleanField(default=False, verbose_name='Tüm turlarda göstər')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Transfer/images')),
                ('prise', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Transfer Tur',
                'verbose_name_plural': 'Transfer Turları',
            },
        ),
        migrations.AlterModelOptions(
            name='antalyaimages',
            options={'verbose_name': 'Antalya Tur Şəkil ', 'verbose_name_plural': 'Antalya Turl Şəkiləri'},
        ),
        migrations.CreateModel(
            name='TransferImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('transferimages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.transfer')),
            ],
            options={
                'verbose_name': 'Transfer Tur Şəkil ',
                'verbose_name_plural': 'Transfer Tur Şəkiləri',
            },
        ),
        migrations.CreateModel(
            name='KiralamaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('kiralamaimages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.kiralama')),
            ],
            options={
                'verbose_name': 'Kiralama Tur Şəkil ',
                'verbose_name_plural': 'Kiralama Tur Şəkiləri',
            },
        ),
        migrations.CreateModel(
            name='KemerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('kemerimages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.kemer')),
            ],
            options={
                'verbose_name': 'Kemer Tur Şəkil ',
                'verbose_name_plural': 'Kemer Tur Şəkiləri',
            },
        ),
        migrations.CreateModel(
            name='BelekImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('belekimages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.belek')),
            ],
            options={
                'verbose_name': 'Belek Tur Şəkil ',
                'verbose_name_plural': 'Antalya Tur Şəkiləri',
            },
        ),
        migrations.CreateModel(
            name='AlanyaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('alanyaimages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.alanya')),
            ],
            options={
                'verbose_name': 'Alanya Tur Şəkil ',
                'verbose_name_plural': 'Alanya Tur Şəkiləri',
            },
        ),
    ]
