# Generated by Django 3.2.7 on 2021-09-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_auto_20210923_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antalyaimages',
            options={'verbose_name': 'Antalya Tur Şəkil ', 'verbose_name_plural': 'Antalya Tur Şəkiləri'},
        ),
        migrations.AlterModelOptions(
            name='belekimages',
            options={'verbose_name': 'Belek Tur Şəkil ', 'verbose_name_plural': 'Belek Tur Şəkiləri'},
        ),
    ]
