# Generated by Django 3.2.7 on 2021-09-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_auto_20210923_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alanyaimages',
            name='picture',
            field=models.ImageField(upload_to='Alanya/images'),
        ),
        migrations.AlterField(
            model_name='antalyaimages',
            name='picture',
            field=models.ImageField(upload_to='Antalya/images'),
        ),
        migrations.AlterField(
            model_name='belekimages',
            name='picture',
            field=models.ImageField(upload_to='Belek/images'),
        ),
        migrations.AlterField(
            model_name='kemerimages',
            name='picture',
            field=models.ImageField(upload_to='Kemer/images'),
        ),
        migrations.AlterField(
            model_name='kiralamaimages',
            name='picture',
            field=models.ImageField(upload_to='Kiralama/images'),
        ),
        migrations.AlterField(
            model_name='transferimages',
            name='picture',
            field=models.ImageField(upload_to='Transfer/images'),
        ),
    ]
