# Generated by Django 3.2.7 on 2021-09-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_auto_20210923_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='antalya',
            name='calendar',
            field=models.CharField(choices=[('everyday', 'hər gün'), ('monday', 'bazar ertəsi'), ('tuesday', 'çərşənbə axşamı'), ('wednesday', 'çərşənbə'), ('thursday', 'cümə axşamı'), ('friday', 'cümə'), ('saturday', 'şənbə'), ('sunday', 'bazar')], default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
