# Generated by Django 3.2.7 on 2021-09-23 18:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0016_antalya_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Gün',
                'verbose_name_plural': 'Günlər',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_popular', models.BooleanField(default=False, verbose_name='Tüm turlarda göstər')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='tour/images')),
                ('price', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('days', models.ManyToManyField(to='tour.Day', verbose_name='Günlər')),
            ],
            options={
                'verbose_name': 'Tur',
                'verbose_name_plural': 'Turlar',
            },
        ),
    ]
