# Generated by Django 3.2.7 on 2021-09-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0018_tourimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Ölkə',
                'verbose_name_plural': 'Ölkələr',
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.country', verbose_name='Günlər'),
            preserve_default=False,
        ),
    ]
