# Generated by Django 3.2.7 on 2021-09-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0019_auto_20210923_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.country', verbose_name='Ölkə'),
        ),
    ]
