# Generated by Django 3.2.7 on 2021-09-24 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0020_alter_tour_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alanyaimages',
            name='alanyaimages',
        ),
        migrations.RemoveField(
            model_name='antalyaimages',
            name='antalyaimages',
        ),
        migrations.RemoveField(
            model_name='belekimages',
            name='belekimages',
        ),
        migrations.RemoveField(
            model_name='kemerimages',
            name='kemerimages',
        ),
        migrations.RemoveField(
            model_name='kiralamaimages',
            name='kiralamaimages',
        ),
        migrations.RemoveField(
            model_name='transferimages',
            name='transferimages',
        ),
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.reservation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to='Tour/images'),
        ),
        migrations.DeleteModel(
            name='Alanya',
        ),
        migrations.DeleteModel(
            name='AlanyaImages',
        ),
        migrations.DeleteModel(
            name='Antalya',
        ),
        migrations.DeleteModel(
            name='AntalyaImages',
        ),
        migrations.DeleteModel(
            name='Belek',
        ),
        migrations.DeleteModel(
            name='BelekImages',
        ),
        migrations.DeleteModel(
            name='Kemer',
        ),
        migrations.DeleteModel(
            name='KemerImages',
        ),
        migrations.DeleteModel(
            name='Kiralama',
        ),
        migrations.DeleteModel(
            name='KiralamaImages',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.DeleteModel(
            name='TransferImages',
        ),
    ]
