# Generated by Django 3.2.7 on 2021-09-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0021_auto_20210924_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='name',
        ),
    ]
