# Generated by Django 3.2.7 on 2021-09-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0022_remove_tour_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.reservation'),
            preserve_default=False,
        ),
    ]
