# Generated by Django 3.2.7 on 2021-09-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0023_tour_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
            preserve_default=False,
        ),
    ]
