# Generated by Django 3.2.7 on 2021-09-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0024_auto_20210924_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='name_tour',
        ),
    ]
