# Generated by Django 3.2.7 on 2021-09-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0025_rename_name_reservation_name_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='name_tour',
            field=models.ForeignKey(db_column='title', on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
        ),
    ]
