# Generated by Django 3.2.7 on 2021-09-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0027_alter_reservation_name_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='name_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
        ),
    ]
